import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Character } from '../types'
import { useRouter } from 'next/router'
import imageLoader from '../imageLoader'
import styles from '../styles/Home.module.css'
import { GetStaticProps, NextPage } from 'next'

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  const router = useRouter();

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {characters.map((character) => {
          return <div key={character.id}><Link href={`/characters/${character.id}`}><h3>{character.name}</h3></Link>
            <Image
              loader={imageLoader}
              unoptimized
              src={character.image}
              alt={character.name}
              height={200}
              width={200}
            />
          </div>
        })}
      </div>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character")
  const { results } = await res.json();

  return {
    props: {
      characters: results
    }
  }
}

export default Home;